[package]
name = "dane-updater"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.86"
base16 = "0.2.1"
clap = { version = "4.5.11", features = ["derive"] }
data-encoding = "2.6.0"
der = { version = "0.7.9", features = ["std"] }
digest = "0.10.7"
env_logger = "0.11.5"
hickory-client = { version = "0.24.1", features = ["dnssec", "dnssec-ring"] }
hickory-proto = { version = "0.24.1", features = ["dnssec"] }
hickory-resolver = { version = "0.24.1", features = ["system-config"] }
hmac = "0.12.1"
log = "0.4.22"
pkcs8 = "0.10.2"
rustls-pemfile = "2.1.3"
sec1 = { version = "0.7.3", features = ["pkcs8"] }
serde = { version = "1.0.215", features = ["derive"] }
sha2 = "0.10.8"
spki = "0.7.3"
toml = "0.8.19"
